name: CI-CD Microservices (Docker Push)

on:
  push:
    branches: ["main"]   # chạy khi push lên main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ===== AUTH SERVICE =====
      - name: Build auth service
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth:latest ./auth

      - name: Push auth service
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth:latest

      # ===== PRODUCT SERVICE =====
      - name: Build product service
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product:latest ./product

      - name: Push product service
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/product:latest

      # ===== ORDER SERVICE =====
      - name: Build order service
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order:latest ./order

      - name: Push order service
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/order:latest

      # ===== API GATEWAY =====
      - name: Build api-gateway service
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest ./api-gateway

      - name: Push api-gateway service
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
